---
- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"

- name: Uninstall CLI version of Docker (if previously installed)
  homebrew:
    name: docker
    state: absent

- name: Install Homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"

