---
# 1. Ensure Homebrew catalogue is fresh
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes
    state: present

# 2. Install OpenJDK 17
- name: Install OpenJDK 17
  community.general.homebrew:
    name: openjdk@17
    state: present

# 3. Link the keg once
- name: Link OpenJDK 17
  command: brew link --force --overwrite openjdk@17
  args:
    creates: "{{ lookup('pipe','brew --prefix') }}/opt/openjdk@17/bin/java"

# 3 b. Register Home‑brew JDK with java_home
- name: Symlink JDK into /Library/Java/JavaVirtualMachines
  become: yes
  file:
    src:  "{{ lookup('pipe','brew --prefix') }}/opt/openjdk@17/libexec/openjdk.jdk"
    dest: /Library/Java/JavaVirtualMachines/openjdk-17.jdk
    state: link


# 4. Export JAVA_HOME in ~/.zshrc
- name: Export JAVA_HOME
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: 'export JAVA_HOME="$(/usr/libexec/java_home -v 17)"'
    create: yes
    state: present

# 5. Verify java works (diagnostic)
- name: Check Java runtime
  command: java -version
  register: java_check
  changed_when: false

